#!/bin/bash

script/branding

set -e

if [[ -z "$TEST_DIR" ]]
then
  echo "Unknown test directory"
  exit 1
else
    cd $TEST_DIR
#    clang -coverage -O0 main.c -o main $ARGS && { [ -z $RUN ] && ./main || echo "skipped ./main"; }
    gcc -coverage $TEST_DIR.c -o $TEST_DIR $ARGS && { [ -z $RUN ] && ./$TEST_DIR || echo "skipped ./$TEST_DIR"; }
    gcov $TEST_DIR.c
    cd -
fi
