#!/bin/bash

script/branding

set -e

if [[ -z "$TEST_DIR" ]]
then
  echo "Unknown test directory"
  exit 1
else
    cd $TEST_DIR
    clang -coverage -O0 $TEST_DIR.c -o $TEST_DIR $ARGS && ./$TEST_DIR $BYPASS_USER_INPUT
    gcov $TEST_DIR.c
    cd -
fi
