#!/bin/bash

echo " ---------------"
echo "      _____     "
echo "     /  __ \    "
echo "    /  /  \_|   "
echo "    | |         "
echo "    | |    _    "
echo "    \  \__/ |   "
echo "     \_____/    "
echo "                "
echo " ---------------"